name = "RiscvDialect"
version = "0.1.0"

defaultTargets = ["RiscvDialect"]

[[lean_lib]]
name = "RiscvDialect"

[[require]]
name = "SSA"
git = "https://github.com/opencompl/lean-mlir.git"
rev = "changeTransformError"

[[require]]
name = "Lean_RV64D_LEAN"
git = "https://github.com/opencompl/sail-riscv-lean.git"
rev = "forSarah"

[[lean_exe]]
name = "RiscvDialectExe"
root = "RiscvDialect"

[[lean_exe]]
name = "opt2"
root = "RiscvDialect.LLVMRiscv.Opt2"
supportInterpreter = true