name = "RiscvDialect"
version = "0.1.0"
defaultTargets = ["RiscvDialect"]

[[lean_lib]]
name = "RiscvDialect"

[[require]]
name = "SSA"
git = "https://github.com/opencompl/lean-mlir.git"
rev = "main"

[[require]]
name = "Lean_RV64D_LEAN"
git = "https://github.com/opencompl/sail-riscv-lean.git"
rev = "forSarah"
